// Mocks generated by Mockito 5.1.0 from annotations
// in vest_store/test/modules/product/domain/usercases/get_all_products_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vest_store/modules/product/core/errors/errors.dart' as _i5;
import 'package:vest_store/modules/product/domain/entities/product_entity.dart'
    as _i6;
import 'package:vest_store/modules/product/domain/repositories/products_respository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i3.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.FailuresProducts, List<_i6.ProductsEntity>?>>
      product() => (super.noSuchMethod(Invocation.method(#product, []),
          returnValue:
              Future<_i2.Either<_i5.FailuresProducts, List<_i6.ProductsEntity>?>>.value(
                  _FakeEither_0<_i5.FailuresProducts,
                      List<_i6.ProductsEntity>?>())) as _i4
          .Future<_i2.Either<_i5.FailuresProducts, List<_i6.ProductsEntity>?>>);
}
